### ISSUE TITLE
[제안요청]GTK 파일매니저(탐색기)에서 마우스 우클릭 메뉴를 통한 파일전송 기능 구현 방법

### ISSUE THREAD

**Issue by HuneOpenUp** [HuneOpenUp/ossFileTransferClient#1]
본 프로젝트에서는 개방형OS 공통으로 GTK(3.7 이상) 기반으로 개발합니다.
마우스우클릭 기능은 파일매니저(탐색기)에서 선택한 파일(파일, 폴더를 포함한 다중 선택까지)마우스우클릭 메뉴(ex, 업무망으로 파일 보내기)를 표시하고, 메뉴 선택 시 선택된 파일들을 대상으로 파일전송 기능을 링크할 수 있는 기능입니다.
이에 대해서는 다양한 방법들을 검토하여 테스트중이며, 귀하의 의견을 듣고자 합니다.

개방형OS에서 GTK 기반으로 마우스우클릭(Context Menu) 구현 방안에 대한 아이디어나 샘플이 있으면 제출해 주시기 바랍니다.

**Comment by LeeJeKyoung** [comment]
우분투 (데비안)기반 노틸러스 파일 매니저에서 사용할 수 있는 방법
1. Nautilus Script
 ~/.local/share/nautilus/scripts 경로에 shell스크립트 파일을 생성

2. Nautilus Actions
 nautilus-actions-config-tool을 이용하여 Right Context Menu를 생성

3. python-nautilus extension
 python을 이용하여 코드 작성 

--
자세한 내용은 아래의 스택오버플로우 링크를 참조하시길 바랍니다.
https://askubuntu.com/questions/21953/how-do-i-customize-the-context-menu-in-nautilus
