### ISSUE TITLE
About HTTP parameter processing

### ISSUE THREAD

**Issue by mdsnins** [HuneOpenUp/ossFileTransferClient#8]
https://github.com/HuneOpenUp/ossFileTransferClient/blob/8a31eecf2bc375f6e6cd7e94ec314d80ab4a9f23/src/src/core/http.cpp#L195-L197

`http_param_append` 함수에서 `value`에 URL encoding을 수행할 필요가 있을 듯 합니다.

**Comment by LeeJeKyoung** [comment]
수정하여 풀리퀘스트 요청 주시면 반영하겠습니다.

**Comment by LeeJeKyoung** [comment]
Merge 하였으므로 이슈 종료합니다.
